name: Catalogo Conecta Automation
on:
  schedule:
    - cron: "0 13 * * *" # 8:00 AM hora de Lima
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Deps
        run: pip install Pillow pandas gspread oauth2client requests
      - name: Run Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python main.py
      - name: Push Designs
        run: |
          git config --global user.name "Elias-Martech-Bot"
          git config --global user.email "analytics.data.jg.2025@gmail.com"
          
          # 1. Traer cambios remotos para evitar el error de 'rejected'
          git pull origin main --rebase
          
          # 2. Agregar los archivos de la carpeta output
          git add output/*
          
          # 3. Hacer el commit
          git commit -m "Auto-generaci√≥n de piezas - $(date -u -d '5 hours ago' '+%Y-%m-%d %H:%M')" || echo "Sin cambios"
          
          # 4. Subir
          git push origin main